version: '3.7'
services:
  dbeaver:
    build: app
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY:0
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    build: db
    ports:
      - 1433
    healthcheck:
      test: "pwd"
